ignore:
  - "app/Http/Controllers/Auth"
  - "app/Http/Middleware/Authenticate.php"
  - "app/Http/Middleware/RedirectIfAuthenticated.php"
  - "app/Exceptions/Handler.php"
  - "app/Providers/BroadcastServiceProvider.php"