filter:
  paths:
    - "app/"
  excluded_paths:
    - "app/Http/Controllers/Auth"
    - "app/Http/Middleware/Authenticate.php"
    - "app/Http/Middleware/RedirectIfAuthenticated.php"
    - "app/Exceptions/Handler.php"
    - "app/Providers/BroadcastServiceProvider.php"
build:
  environment:
    php: '7.2'
    node: '8.1'
    hosts:
      laravel.dev: '127.0.0.1'
    variables:
      APP_ENV: 'testing'
      APP_URL: 'http://laravel.dev'
      API_HOST: 'laravel.dev'
      MAIL_DRIVER: 'log'
  cache:
    directories:
      - node_modules
      - vendor/
      - ~/.composer/cache/
  dependencies:
    before:
      - cp .env.ci .env
      - composer self-update
      - composer install --no-interaction
      - chmod -R 777 storage
      - chmod -R 777 bootstrap/cache
      - rm -rf node_modules
      - npm install
      - npm run production
      - php artisan key:generate
  tests:
    override:
      - vendor/bin/php-cs-fixer fix app --dry-run --rules=@PSR2
      -
        command: vendor/bin/phpunit --testdox --coverage-clover=clover-coverage
        coverage:
          file: clover-coverage
          format: clover