language: php

php:
  - 7.2
  - 7.3

node:
  - 8.1

branches:
  only:
    - master
    - develop

before_script:
  - cp .env.ci .env
  - composer self-update
  - composer install --no-interaction
  - chmod -R 777 storage
  - chmod -R 777 bootstrap/cache
  - rm -rf node_modules
  - npm install
  - npm run production
  - php artisan key:generate

script:
  - vendor/bin/php-cs-fixer fix app --dry-run --rules=@PSR2
  - vendor/bin/phpunit

after_script:
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

cache:
  directories:
    - vendor
    - node_modules